### ISSUE TITLE
Pages requesting data from TikTok show 500 error when not in legacy mode

### ISSUE THREAD

**Issue by N-Upchurch** [YunoHost-Apps/proxitok_ynh#1]
When accessing any page that requests data from TikTok, such as Trending, or individual user pages, a 500 error is returned when not in legacy mode. Switching to legacy mode in settings allows these pages to return expected results.

**Comment by ericgaspar** [comment]
cf. the issue upstream https://github.com/pablouser1/ProxiTok/issues/21

we can force the legacy mode in the .env as default #2

**Comment by N-Upchurch** [comment]
Understood, thanks!
