### ISSUE TITLE
ProxiTok failing to update : the package yunohost (4.4.2.6) must be >= 11.0.9

### ISSUE THREAD

**Issue by Wintburr** [YunoHost-Apps/proxitok_ynh#14]
Hi! Thank you for porting ProxiTok to Yunohost, I appreciate the work.

Seems like commit 5b43148abd1c03e1627573b7c3d87289f2b7275b broke the install and upgrading process as the manifest.json file mentions Yunohost 11.0.9 or more as a requirement, whereas even the latest version is only 4.4.2.6.

Hopefully it is an easy fix, and thank you for your work!

**Comment by ericgaspar** [comment]
This is not a bug... you should update your server.
YunoHost as been updated to Bullseye. I have updated the ProxiTok requirements to YunoHost 11.0.9 because it has some PHP helper improvements that solve issues like #5.

**Comment by Wintburr** [comment]
Heck, I made sure to upgrade Yunohost before sending this, no idea why it didn't say anything about upgrading to Bullseye 😅
Sorry about that, but thank you very much!
