### ISSUE TITLE
Proxitok with yunohost not working

### ISSUE THREAD

**Issue by mg-dev25** [YunoHost-Apps/proxitok_ynh#21]
Hi, I don't know if Proxitok really work with YunoHost, because It is not working with any of the update. And there are no service for this app so no log for debugging. Is this app still used or it just on auto update mode?

Thanks.

Here is a link of the installation, if it can help.

https://paste.yunohost.org/raw/kagosizana

**Comment by SolainOG** [comment]
I get the front page running but server returns 500 for any search I try to make. Is this integration tested?

**Comment by Handrail9** [comment]
Same issue here, seems like this app isn't really tested or kept up with

**Comment by ericgaspar** [comment]
Thanks for reporting. I changed the status as not working in the catalog.
